"use client";

import { Suspense, useState } from "react";
import Link from "next/link";
import { Inter } from "next/font/google";
import { Menu, X } from "lucide-react";
import "../styles/affsense-premium-landing.css";
import { ReferralCapture } from "./referral-capture";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-inter",
  display: "swap",
});

const SECTION_LINKS = [
  { href: "#opportunities", label: "Ways to Earn" },
  { href: "#products", label: "Digital Products" },
  { href: "#how", label: "How It Works" },
  { href: "#payouts", label: "Payouts" },
  { href: "#faq", label: "FAQ" },
] as const;

const OPPORTUNITIES = [
  {
    icon: "🛍️",
    tag: "CORE OPPORTUNITY",
    title: "1. Promote Digital Products",
    body: "Browse a marketplace of low-ticket digital products such as courses, ebooks, AI prompt packs, social media graphic packs, Reels packs and business resources. Choose a product, generate your affiliate link and send visitors to its ready-made sales funnel.",
    items: [
      "Planned 80% commission on eligible front-end sales.",
      "Planned 50% commission on eligible funnel upsells.",
      "Ready-to-use promotional materials where available.",
      "Clicks, sales and commissions tracked in Affsense.",
    ],
    earnLabel: "Designed for",
    earnValue: "Affiliates • Creators • Beginners",
  },
  {
    icon: "🎯",
    tag: "PERFORMANCE",
    title: "2. Promote CPA Offers",
    body: "Access eligible CPA campaigns from the Affsense marketplace. Instead of always requiring a product purchase, qualifying campaigns may pay for an approved lead, registration, action or sale.",
    items: [
      "View payout, geography and conversion requirements before promoting.",
      "Use a unique tracking link with Sub ID reporting.",
      "Review clicks, conversions, EPC and commissions.",
      "Traffic-source and campaign restrictions shown per offer.",
    ],
    earnLabel: "How earnings work",
    earnValue: "Offer-Specific CPA Payout",
  },
  {
    icon: "⚡",
    tag: "QUICK EARN",
    title: "3. Get Paid for Tasks",
    body: "Complete eligible digital jobs with a clearly displayed reward before you begin. Tasks can include legitimate content creation, research, feedback, testing, graphics or other advertiser-funded work.",
    items: [
      "See task reward and requirements upfront.",
      "Submit proof or deliverables directly through Affsense.",
      "Track Pending, Approved or Rejected status.",
      "Approved rewards move into your earnings balance.",
    ],
    earnLabel: "How earnings work",
    earnValue: "Fixed Reward Per Approved Task",
  },
  {
    icon: "▦",
    tag: "OFFER WALL",
    title: "4. Complete Offer Wall Opportunities",
    body: "Explore third-party opportunities made available through integrated Offer Wall providers. Depending on the campaign, qualifying actions may include surveys, registrations, app interactions or other approved activities.",
    items: [
      "Browse available opportunities from one dashboard.",
      "Reward and requirements displayed before participation.",
      "Availability can vary by country and user eligibility.",
      "Validated rewards are reflected in the Affsense wallet.",
    ],
    earnLabel: "How earnings work",
    earnValue: "Opportunity-Specific Reward",
  },
  {
    icon: "👥",
    tag: "LIFETIME DIRECT",
    title: "5. Refer New Affsense Members",
    body: "Share your unique referral link and introduce other people to the free Affsense platform. Under the planned model, you can receive a 10% one-level lifetime reward on defined eligible product sales generated by your direct referrals.",
    items: [
      "No membership purchase required to refer someone.",
      "One-level direct referral structure.",
      "Referral activity and qualifying rewards tracked in your dashboard.",
      "Reward applies according to published compensation terms.",
    ],
    earnLabel: "Planned reward",
    earnValue: "10% on Defined Eligible Sales*",
  },
  {
    icon: "🎥",
    tag: "CREATOR JOBS",
    title: "6. Content & Creator Opportunities",
    body: "Where available, members can take on higher-value creator work such as original social posts, graphics, short-form videos, UGC-style content, campaign assets or product feedback for participating advertisers.",
    items: [
      "Clear creative brief before accepting the job.",
      "Upload deliverables through the task workflow.",
      "Advertiser/admin review and approval process.",
      "Higher-value jobs can carry larger fixed rewards.",
    ],
    earnLabel: "How earnings work",
    earnValue: "Fixed / Campaign-Based Reward",
  },
] as const;

const PRODUCT_FEATURES = [
  {
    title: "Ready-made product funnels",
    desc: "No need to create your own sales page or checkout.",
  },
  {
    title: "High affiliate commissions",
    desc: "Planned 80% front-end and 50% eligible upsell commissions.",
  },
  {
    title: "Promotion center",
    desc: "Access approved emails, social copy, banners and video ideas where provided.",
  },
  {
    title: "Performance reporting",
    desc: "Track clicks, sales, conversion rate and commissions from one account.",
  },
] as const;

const FEATURED_PRODUCTS = [
  { thumb: "AI", name: "AI Prompt Vault", meta: "AI Tools • Digital Product" },
  { thumb: "IG", name: "Instagram Reels Pack", meta: "Social Media • Digital Product" },
  { thumb: "EM", name: "Email Marketing Toolkit", meta: "Marketing • Digital Product" },
  { thumb: "YT", name: "YouTube Growth Guide", meta: "Creator • Digital Product" },
] as const;

const STEPS = [
  {
    num: "01",
    title: "Create a Free Account",
    body: "Register, complete your profile and set up your account.",
  },
  {
    num: "02",
    title: "Choose How to Earn",
    body: "Browse products, CPA campaigns, tasks, Offer Wall opportunities or referrals.",
  },
  {
    num: "03",
    title: "Promote or Complete",
    body: "Use your tracking link and promotional assets or complete the stated job requirements.",
  },
  {
    num: "04",
    title: "Track & Withdraw",
    body: "Follow pending and approved earnings and request eligible payouts.",
  },
] as const;

const BACKEND_CARDS = [
  {
    title: "📊 Performance Reports",
    body: "Review clicks, conversions, product sales, task results, referral activity and payout history.",
  },
  {
    title: "📣 Promotion Resources",
    body: "Access approved promotional copy, creative assets and campaign guidance where available.",
  },
  {
    title: "🎓 Training Center",
    body: "Learn how tracking links, affiliate disclosures, traffic sources, products and CPA campaigns work.",
  },
  {
    title: "🔔 Announcements",
    body: "See new products, new CPA campaigns, task availability, payout notices and platform updates.",
  },
] as const;

const FAQS: { q: string; a: string; open?: boolean }[] = [
  {
    q: "Is Affsense free to join?",
    a: "Yes. The planned member account is free. Individual campaigns or earning opportunities may have eligibility, geographic, traffic-source or verification requirements.",
    open: true,
  },
  {
    q: "What commission can I earn from digital products?",
    a: "The current planned model is 80% on eligible front-end digital product sales and 50% on eligible upsells. Each listing should show its exact commission and terms before promotion.",
  },
  {
    q: "What are CPA offers?",
    a: "CPA campaigns pay for a specified qualifying action, which may be an approved lead, registration, sale or another defined conversion. Payout and traffic rules vary by offer.",
  },
  {
    q: "What kind of paid tasks can appear?",
    a: "Eligible tasks can include legitimate content creation, research, product or landing-page feedback, testing, graphics and similar digital work. Affsense should not permit fake reviews, spam manipulation or deceptive engagement tasks.",
  },
  {
    q: "What is the Offer Wall?",
    a: "The Offer Wall can display integrated third-party opportunities. Availability and rewards may vary by country, provider and user eligibility, and credit is subject to successful tracking and validation.",
  },
  {
    q: "How does the referral reward work?",
    a: "Under the planned one-level model, members can receive a 10% lifetime reward on the defined eligible product sales generated by direct referrals. The exact eligible sales base and exclusions should be stated in the published compensation terms.",
  },
  {
    q: "When do payouts happen?",
    a: "The current plan is weekly payouts with a $20 minimum threshold. Earnings can remain pending while conversions, tasks, refunds or fraud checks are being validated.",
  },
  {
    q: "Does Affsense guarantee income?",
    a: "No. Earnings depend on actual qualifying activity, conversions, traffic, task availability, eligibility and other factors. No specific income or result is guaranteed.",
  },
];

const SIDE_ITEMS = [
  "Dashboard",
  "Marketplace",
  "Get Paid Tasks",
  "Offer Wall",
  "CPA Offers",
  "Referrals",
  "Earnings",
  "Payouts",
  "Reports",
] as const;

function Logo({ href = "/" }: { href?: string }) {
  return (
    <Link className="logo" href={href}>
      <span className="logoMark">A</span>
      <span className="logoWord">
        Aff<span>sense</span>
      </span>
    </Link>
  );
}

export function AffsensePremiumLandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);

  function closeMenu() {
    setMenuOpen(false);
  }

  return (
    <div className={`affsensePremium ${inter.variable}`}>
      <Suspense fallback={null}>
        <ReferralCapture />
      </Suspense>

      <header className="nav">
        <div className="container navin">
          <Logo />
          <nav className="navlinks" aria-label="Primary">
            {SECTION_LINKS.map((link) => (
              <a key={link.href} href={link.href}>
                {link.label}
              </a>
            ))}
          </nav>
          <div className="navbtns">
            <Link className="btn btnLight" href="/login">
              Member Login
            </Link>
            <Link className="btn btnPrimary" href="/register">
              Join Free →
            </Link>
            <button
              type="button"
              className="mobileMenuToggle"
              aria-label={menuOpen ? "Close menu" : "Open menu"}
              aria-expanded={menuOpen}
              onClick={() => setMenuOpen((open) => !open)}
            >
              {menuOpen ? <X size={22} /> : <Menu size={22} />}
            </button>
          </div>
        </div>
        {menuOpen ? (
          <div className="mobileNavPanel isOpen" role="dialog" aria-label="Mobile navigation">
            <div className="container">
              {SECTION_LINKS.map((link) => (
                <a key={link.href} href={link.href} onClick={closeMenu}>
                  {link.label}
                </a>
              ))}
              <div className="mobileNavActions">
                <Link className="btn btnLight" href="/login" onClick={closeMenu}>
                  Member Login
                </Link>
                <Link className="btn btnPrimary" href="/register" onClick={closeMenu}>
                  Join Free →
                </Link>
              </div>
            </div>
          </div>
        ) : null}
      </header>

      <main>
        <section className="hero">
          <div className="container heroGrid">
            <div>
              <div className="badge">
                <span className="badgeDot" />
                FREE MEMBERSHIP • MULTIPLE EARNING OPPORTUNITIES
              </div>
              <h1>
                One Platform.
                <br />
                <span className="grad">Multiple Ways to Earn Online.</span>
              </h1>
              <p>
                Affsense brings digital product commissions, CPA offers, paid tasks, Offer Wall
                opportunities and direct referral rewards together in one easy-to-use earning
                dashboard.
              </p>
              <div className="heroBtns">
                <Link className="btn btnPrimary" href="/register">
                  Create My Free Account →
                </Link>
                <a className="btn btnLight" href="#opportunities">
                  Explore Earning Options
                </a>
              </div>
              <div className="checksInline">
                <span>Free to join</span>
                <span>Multiple earning paths</span>
                <span>Weekly payout cycle</span>
                <span>$20 planned minimum</span>
              </div>
            </div>

            <div className="dashboard" aria-hidden="true">
              <div className="dashTop">
                <div className="dashLogo">
                  Aff<span>sense</span>{" "}
                  <small style={{ color: "#999", fontWeight: 500 }}>Affiliate Panel</small>
                </div>
                <div className="dashUser">
                  <div className="avatar">AL</div> My Account
                </div>
              </div>
              <div className="dashBody">
                <aside className="dashSide">
                  {SIDE_ITEMS.map((item, index) => (
                    <div key={item} className={`sideItem${index === 0 ? " active" : ""}`}>
                      {item}
                    </div>
                  ))}
                </aside>
                <div className="dashMain">
                  <div className="dashTitle">Welcome back 👋</div>
                  <div className="dashCards">
                    <div className="dashCard">
                      <small>Total Earnings</small>
                      <strong>$2,483.67</strong>
                      <em>Illustrative UI</em>
                    </div>
                    <div className="dashCard">
                      <small>Available Balance</small>
                      <strong>$416.50</strong>
                      <em>Example</em>
                    </div>
                    <div className="dashCard">
                      <small>Total Referrals</small>
                      <strong>142</strong>
                      <em>Example</em>
                    </div>
                  </div>
                  <div className="chart">
                    <b>Earnings Overview</b>
                    <svg viewBox="0 0 500 110" preserveAspectRatio="none">
                      <defs>
                        <linearGradient id="affsensePremiumFill" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0" stopColor="#FF6B6B" stopOpacity=".22" />
                          <stop offset="1" stopColor="#FF6B6B" stopOpacity="0" />
                        </linearGradient>
                      </defs>
                      <path
                        d="M0 94 C45 91 65 78 105 84 S150 58 195 70 S240 25 290 45 S350 12 395 39 S450 67 500 18 L500 110 L0 110Z"
                        fill="url(#affsensePremiumFill)"
                      />
                      <path
                        d="M0 94 C45 91 65 78 105 84 S150 58 195 70 S240 25 290 45 S350 12 395 39 S450 67 500 18"
                        fill="none"
                        stroke="#FF6B6B"
                        strokeWidth="3"
                      />
                    </svg>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="metricbar">
          <div className="container metrics">
            <div className="metric">
              <strong>80%</strong>
              <span>Planned digital product FE commission</span>
            </div>
            <div className="metric">
              <strong>50%</strong>
              <span>Planned eligible upsell commission</span>
            </div>
            <div className="metric">
              <strong>10%</strong>
              <span>Planned direct referral reward*</span>
            </div>
            <div className="metric">
              <strong>Weekly</strong>
              <span>Planned payouts from $20</span>
            </div>
          </div>
        </section>

        <section className="section soft" id="opportunities">
          <div className="container">
            <div className="center">
              <div className="kicker">The Affsense Earning Ecosystem</div>
              <h2>Every Income Opportunity, Inside One Account</h2>
              <p className="lead">
                Some members prefer selling, some prefer performance marketing, and others want
                straightforward tasks. Affsense is designed to let members choose the opportunity that
                matches their skills, audience and available time.
              </p>
            </div>
            <div className="opportunities">
              {OPPORTUNITIES.map((opp) => (
                <article key={opp.title} className="opp">
                  <div className="oppTop">
                    <div className="oppIcon">{opp.icon}</div>
                    <span className="oppTag">{opp.tag}</span>
                  </div>
                  <h3>{opp.title}</h3>
                  <p>{opp.body}</p>
                  <div className="miniList">
                    {opp.items.map((item) => (
                      <div key={item} className="miniItem">
                        <span className="miniCheck">✓</span>
                        {item}
                      </div>
                    ))}
                  </div>
                  <div className="earnBox">
                    <span>{opp.earnLabel}</span>
                    <strong>{opp.earnValue}</strong>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="section" id="products">
          <div className="container marketGrid">
            <div className="copy">
              <div className="kicker">Digital Product Marketplace</div>
              <h2>Choose a Product. Get Your Link. Start Promoting.</h2>
              <p>
                The product marketplace is designed as the simplest path for members who want to earn
                affiliate commissions. Affsense lists the opportunity while the external sales funnel
                handles checkout and product delivery.
              </p>
              <div className="featureList">
                {PRODUCT_FEATURES.map((feature) => (
                  <div key={feature.title} className="feature">
                    <div className="circleCheck">✓</div>
                    <div>
                      <b>{feature.title}</b>
                      <span>{feature.desc}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="marketCard">
              <div className="marketHead">
                <b>Featured Digital Products</b>
                <span className="live">MARKETPLACE</span>
              </div>
              {FEATURED_PRODUCTS.map((product) => (
                <div key={product.name} className="offer">
                  <div className="thumb">{product.thumb}</div>
                  <div>
                    <b>{product.name}</b>
                    <small>{product.meta}</small>
                  </div>
                  <div className="offerPay">
                    <strong>80%</strong>
                    <span>FE commission</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="section soft" id="how">
          <div className="container">
            <div className="center">
              <div className="kicker">Simple by Design</div>
              <h2>From Free Signup to Earning Opportunity</h2>
              <p className="lead">
                Affsense is designed to make the next action obvious, even for members who are new to
                affiliate and performance marketing.
              </p>
            </div>
            <div className="steps">
              {STEPS.map((step) => (
                <div key={step.num} className="step">
                  <div className="stepNum">{step.num}</div>
                  <h3>{step.title}</h3>
                  <p>{step.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="section" id="payouts">
          <div className="container">
            <div className="dark">
              <div>
                <div className="kicker">Affsense Wallet</div>
                <h2>Clear Earnings. Simple Payout Tracking.</h2>
                <p>
                  Your dashboard separates pending, approved and available balances so you know what
                  has been tracked, what is under validation and what is eligible for withdrawal. The
                  current plan is a weekly payout cycle with a $20 minimum threshold.
                </p>
                <Link className="btn btnPrimary" href="/register">
                  Join Affsense Free →
                </Link>
              </div>
              <div className="balance">
                <small>AVAILABLE BALANCE — ILLUSTRATIVE UI</small>
                <strong>$416.50</strong>
                <div className="balanceRow">
                  <span>Pending Earnings</span>
                  <b>$634.25</b>
                </div>
                <div className="balanceRow">
                  <span>Planned Payout Cycle</span>
                  <b>Weekly</b>
                </div>
                <div className="balanceRow">
                  <span>Planned Minimum</span>
                  <b>$20.00</b>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="section soft">
          <div className="container">
            <div className="center">
              <div className="kicker">More Than an Offer List</div>
              <h2>Tools That Help Members Take Action</h2>
              <p className="lead">
                The goal is to give members both earning opportunities and the information needed to
                use them responsibly.
              </p>
            </div>
            <div className="backend">
              {BACKEND_CARDS.map((card) => (
                <div key={card.title} className="backCard">
                  <h3>{card.title}</h3>
                  <p>{card.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="section" id="faq">
          <div className="container">
            <div className="center">
              <div className="kicker">Frequently Asked Questions</div>
              <h2>Know How Affsense Works Before You Start</h2>
              <p className="lead">
                Transparent rules and clear opportunity details are part of the platform experience.
              </p>
            </div>
            <div className="faq">
              {FAQS.map((item) => (
                <details key={item.q} open={item.open ?? false}>
                  <summary>{item.q}</summary>
                  <p>{item.a}</p>
                </details>
              ))}
            </div>
          </div>
        </section>

        <section className="final">
          <div className="container">
            <div className="kicker">Free to Join</div>
            <h2>
              One Account. Multiple Opportunities.
              <br />
              Start Exploring Affsense.
            </h2>
            <p>
              Create your free account, open your earning dashboard and choose the opportunities that
              best fit your skills, audience and goals.
            </p>
            <Link className="btn btnPrimary" href="/register">
              Create My Free Account →
            </Link>
          </div>
        </section>
      </main>

      <footer>
        <div className="container">
          <div className="foot">
            <Logo />
            <div className="footlinks">
              <a href="/termsofservice.html">Terms</a>
              <a href="/privacy.html">Privacy</a>
              <a href="/termsofservice.html">Affiliate Terms</a>
              <a href="#legal">Earnings Disclaimer</a>
              <a href="mailto:support@leadvix.io">Support</a>
              <Link href="/login">Login</Link>
            </div>
          </div>
          <div className="legal" id="legal">
            *Commission rates, referral rewards, offer availability and payout schedules are subject
            to Affsense terms and individual campaign rules. Dollar amounts and dashboard statistics
            displayed on this page are illustrative interface examples only and are not actual member
            earnings or guarantees. Earnings vary based on qualifying activity, traffic, conversions,
            task availability and other factors. Members must comply with applicable laws, advertising
            rules, affiliate disclosure requirements and traffic-source policies.
          </div>
        </div>
      </footer>
    </div>
  );
}
